---
- name: Test Webhook
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Test Hook2
      community.general.discord:
        webhook_id: "962895744476528710"
        webhook_token: "z6B0SOfjq_HYYvdQgk-JPf2vE_3AF7u7URa7x5dEwvA21NbeO5kA1UT9aVonXCc_x3pb"
        content: "Hello"
        username: "Net"
        avatar_url: 
      register: print_output
    - debug: var=print_output

    - name: HOOK ONE
      community.general.discord:
        webhook_id: "962895864127447040"
        webhook_token: "lxdsfeC1L17MFjoD2vHf2ZEh9GUCP-MkIKIDOyXTEOndYc08TenA-yqfidENfb8WIBG3"
        avatar_url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
        username: TestNet
        embeds:
          - title: "Embed TWO"
            description: "This is my first second message"
            color: 65518
            footer:
              text: "Network Nick"
              icon_url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
            image:
              url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
            fields:
              - name: "Field 1"
                value: "Value of my first field"
              - name: "Field 2"
                value: "Value of my second field"
              - name: "Field 3"
                value: "This is getting redundant"
            timestamp: "{{ ansible_date_time.iso8601 }}"

      register: print_output
    - debug: var=print_output
