---
- name: Test Webhook
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Test Hook2
      community.general.discord:
        webhook_id:
        webhook_token:
        content: "Hello"
        username: "Net"
        avatar_url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
      register: print_output
    - debug: var=print_output

    - name: HOOK ONE
      community.general.discord:
        webhook_id:
        webhook_token:
        avatar_url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
        embeds:
          - title: "Embedded Title"
            description: "Embedded Description"
            footer:
              text: "Embedded Footer Text"
            image:
              url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
          - title: "Embed TWO"
            description: "This is my first second message"
            footer:
              text: "Author: Ansible"
              icon_url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
            image:
              url: "https://cdn2.lamag.com/wp-content/uploads/sites/6/2020/12/dumpster-100soft-mccarty-closeup1-1068x712.jpg"
            fields:
              - name: "Field 1"
                value: "Value of my first field"
              - name: "Field 2"
                value: "Value of my second field"
            timestamp: "{{ ansible_date_time.iso8601 }}"
      register: print_output
    - debug: var=print_output