---
- name: Testing Facts
  hosts: Access1
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Gather all legacy facts
      ios_facts:
        gather_subset: all
      register: output
    - name: Print the subset
      debug:
        var: output

    - name: Gather min facts
      ios_facts:
        gather_subset: min
      register: output
    - name: Print the subset
      debug:
        var: output

    - name: Gather hardware facts
      ios_facts:
        gather_subset: hardware
      register: output
    - name: Print the subset
      debug:
        var: output

    - name: Gather all config facts
      ios_facts:
        gather_subset: config
      register: output
    - name: Print the subset
      debug:
        var: output

- name: Get L2 ints and VLANs
  hosts: Access1
  gather_facts: false
  connection: local

  tasks:
    - name: get L2 ints
      ios_facts:
        gather_network_resources: l2_interfaces
      register: blah
    - name: Print the L2 interfaces
      debug:
        var: blah

    - name: get VLANs
      ios_facts:
        gather_network_resources: vlans
      register: blah
    - name: Print the VLANs
      debug:
        var: blah
