#This should be utilized as an Ansible-vault file in production environments
goodFeatures:
  - lacp
  - ntp
  - udld
  - ospf
  - ospfv3
  - hsrp
  - interface-vlan

badFeatures:
  - telnet
  - wccp
  - imp
  - nxapi
  - vtp

NTP_Servers:
  - Server: 1.1.1.1
    keyNumber: 1
    MD5key: 789789789798
  - Server: 2.2.2.2
    keyNumber: 2
    MD5key: 789789789798

logServers:
  - 192.168.255.10
  - 192.168.254.10

enableSecret: $uper$ecretCompany$tuff666
vtySessionLimit: 2
vtyTimeout: 10
vtyAllowedSubnets:
  - 192.168.1.0 0.0.0.255
  - 192.168.2.0 0.0.0.255
  - 192.168.3.0 0.0.0.255
  - 192.168.255.2 0.0.0.0
  - 192.168.254.2 0.0.0.0