#This should be implemented as an Ansible-vault file in production environments
goodFeatures:
  - lacp
  - ntp
  - udld
  - ospf
  - ospfv3
  - hsrp
  - ssh
  - interface-vlan
  - scp-server
  - port-security

badFeatures:
  - telnet
  - wccp
  - imp
  - nxapi
  - vtp

properHostname: Switch777

NTP_Servers:
  - Server: 1.1.1.1
    keyNumber: 1
    MD5key: 789789789798
  - Server: 2.2.2.2
    keyNumber: 2
    MD5key: 789789789798

logServers:
  - 192.168.255.10
  - 192.168.254.10

portSecMax: 1
enableSecret: $uper$ecretCompany$tuff666
vtySessionLimit: 2
vtyTimeout: 10
vtyAllowedSubnets:
  - networkAddr: 192.168.1.0
    wildcardBits: 0.0.0.255
  - networkAddr: 192.168.2.0
    wildcardBits: 0.0.0.255
  - networkAddr: 192.168.3.0
    wildcardBits: 0.0.0.255
  - networkAddr: 192.168.255.2
    wildcardBits: 0.0.0.0
  - networkAddr: 192.168.254.2
    wildcardBits: 0.0.0.0
