---
- name: Trunk Configuration
  ios_l2_interfaces:
      config:
        - name: "{{ item.portNumber }}"
          mode: trunk
          access:
            - vlan: "{{ nativeVLAN }}"
  loop: "{{ trunk_ports }}"