---
- name: Trunk Configuration
  ios_l2_interfaces:
      config:
        - name: "{{ item.portNumber }}"
          access:
            - native_vlan: "{{ nativeVLAN }}"
              allowed_vlans: "{{ item.allowedVLANList }}"
  loop: "{{ trunk_ports }}"