---
- name: Nexus Device Management Features
  hosts: nexus_switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Harden Access Ports - Storm Control, Port Security, STP
      nxos_config:
        parents: "interface {{ item.portNumber }}"
        lines:
          - switchport block unicast
          - "storm-control broadcast level {{ stormControlBroadcastRising }}"
          - "storm-control multicast level {{ stormControlMulticastRising }}"
          - "storm-control unicast level {{ stormControlUnicastRising }}"
          - storm-control action shutdown
          - spanning-tree port type edge
          - spanning-tree bpduguard enable
          - spanning-tree guard root
          - spanning-tree guard loop
          - "description {{ item.description | default('NOT USED') }}"
          - no shutdown
      loop: "{{ AccessPorts }}"

      - name: Shutdown unused ports
        nxos_config:
          parents: "interface {{ item.portNumber }}"
          lines:
            - shutdown
      loop: "{{ AccessPorts }}"
      when: item.shutdown

- name: Nexus Device Management Features
  hosts: ios_switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Harden Access Ports - Storm Control, Port Security, STP
      ios_config:
        parents: "interface {{ item.portNumber }}"
        lines:
          - switchport block unicast
          - "storm-control broadcast level {{ stormControlBroadcastRising }} {{ stormControlBroadcastFalling}}"
          - "storm-control multicast level {{ stormControlMulticastRising }} {{ stormControlMulticastFalling }}"
          - "storm-control unicast level {{ stormControlUnicastRising }} {{ stormControlUnicastFalling }}"
          - storm-control action shutdown
          - spanning-tree port type edge
          - spanning-tree bpduguard enable
          - spanning-tree guard root
          - spanning-tree guard loop
          - "description {{ item.description | default('NOT USED') }}"
          - no shutdown
      loop: "{{ AccessPorts }}"

      - name: Shutdown unused ports
        ios_config:
          parents: "interface {{ item.portNumber }}"
          lines:
            - shutdown
      loop: "{{ AccessPorts }} 
      when: item.shutdown
