---
- name: Nexus Device Management Features
  hosts: newNexus
  gather_facts: no
  connection: network_cli

    - name: Harden Access Ports - Storm Control, Port Security, STP
      nxos_config:
        parents: "interface {{ item.portNumber }}"
        lines:
          - switchport block unicast
          - "storm-control broadcast level {{ stormControlBroadcast }}"
          - "storm-control multicast level {{ stormControlMulticast }}"
          - "storm-control unicast level {{ stormControlUnicast }}"
          - storm-control action shutdown
          - spanning-tree port type edge
          - spanning-tree bpduguard enable
          - spanning-tree guard root
          - spanning-tree guard loop
          - no shutdown
      loop: "{{ AccessPorts }}"