---
- name:  Create a local administrative account on IOS and IOS XE Devices
  hosts: IOS
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Create IOS and IOS XE Account
      ios_user:
        name: {{ fallbackAdmin }}
        hashed_password:
          type: 5
          value: {{ fallbackAdminPW }}
        privilege: 15
        update_password: always
    
- name:  Create a local administrative account on NXOS Devices
  hosts: NXOS
  gather_facts: false
  connection: local

  tasks:
    - name: Create a local administrative account on NXOS Devices
      nxos_user:
        name: {{ fallbackAdmin }}
        hashed_password:
          type: 5
          value: {{ fallbackAdminPW }}
        role: network-admin
        update_password: always