#designed to be run locally on first boot/configuration of a new Cisco Nexus Switch
---
- name: Nexus Device Management Features
  hosts: newNexus
  gather_facts: no
  connection: network_cli
  vars_files:
    - ./vars/nexusSecurity.yml
    - ./vars/nexusConfig.yml

  tasks:
    - name: Set Correct Hostname
      nxos_config:
        lines:
          - "hostname {{ properHostname }}"

    - name: Enable desired features
      nxos_feature:
        feature: "{{ item }}"
        state: enabled
      loop: "{{ goodFeatures }}"

    - name: Remove unncessary/unsecure features
      nxos_feature:
        feature: "{{ item }}"
        state: disabled
      loop: "{{ badFeatures }}"

    - name: FIPS mode, Password Strength, and Failed Login Blocking
      nxos_config:
        lines:
          - fips mode enable
          - password strength-check
          - login block-for 900 attempts 3 within 180

    - name: Configure Enable Password
      nxos_config:
        lines:
          - "enable secret {{ enableSecret }}"

    - name: Setup Login Banner
      nxos_banner:
        nxos.banner: motd
        text: "{{ lookup('file', './vars/companyBanner.cfg', errors='ignore') }}"
        state: present

    - name: Setup NTP with authentication keys
      cisco.nxos.nxos_ntp_global: #Ansible 2.9 is throwing an error if not using the full module name
        config:
          authenticate: yes
          authentication_keys:
            - encryption: 0
            - id: "{{ item.keyNumber }}"
            - key: "{{ item.MD5key }}"
          trusted keys:
            - key_id: "{{ item.keyNumber }}"
          servers:
            - key_id: "{{ item.keyNumber }}"
            - server: "{{ item.Server }}"
            - use_vrf: default
          logging: yes
        state: merged
      loop: "{{ NTP_Servers }}"

    - name: Set Timezone
      nxos_config:
        lines:
          - clock timezone EST -5 0

#logging server(s)

#logging - lower level to 6 and create logfile w/ manually specified size

#VTY ACL

#VTY session limiting

#VTY/console timeout after X minutes of inactivity

- name: Nexus Switch Functionality
  hosts: newNexus
  gather_facts: no
  connection: network_cli


#VLANs [ including blackhole and native ]

#igmp snooping - all VLANs

#Access Ports
  #unknown unicast flood blocking (UUFB)
  #STP loopguard, rootguard, BPDUguard
  #storm-control broadcast/unicast

#Trunks

#unused ports - shutdown/blackhole vlan
