---
- name: Configure banner
  hosts: IOS, IOSXE
  gather_facts: true
  connection: network_cli

  tasks:
    - name: Setup Login Banner
      ios_banner:
        banner: login
        text: "{{ lookup('file', './resources/banner.cfg', errors='ignore') }}"
        state: present

    - name: Save Config if Changes Made
      ios_config:
        save_when: changed

- name: Configure banner
  hosts: NXOS
  gather_facts: true
  connection: network_cli

  tasks:
    - name: Setup Login Banner
      nxos_banner:
        banner: motd
        text: "{{ lookup('file', './resources/banner.cfg', errors='ignore') }}"
        state: present

    - name: Save Config if Changes Made
      nxos_config:
        save_when: changed
